In [1]:
import pandas as pd 
import numpy as np
df=pd.read_csv('diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [5]:
df.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X=df.drop(['Outcome'],axis='columns')
y=df.Outcome
Scaler=StandardScaler()
X_scale=Scaler.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_scale,y,stratify=y,random_state=10)

In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
score=cross_val_score(DecisionTreeClassifier(),X,y,cv=5)
score

array([0.69480519, 0.67532468, 0.7012987 , 0.81045752, 0.70588235])

In [9]:
score.mean()

0.7175536881419233

# Bagging

In [19]:
from sklearn.ensemble import BaggingClassifier
bag_model=BaggingClassifier(
        base_estimator=DecisionTreeClassifier(),
        n_estimators=100,
        max_samples=0.8,
        oob_score=True,
        random_state=10
)
bag_model.fit(X_train,y_train)

A:\Apps\anaconda\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=DecisionTreeClassifier(), max_samples=0.8,
                  n_estimators=100, oob_score=True, random_state=10)

In [14]:
bag_model.oob_score_

0.7378472222222222

In [15]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(bag_model,X,y,cv=5)
score

A:\Apps\anaconda\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
A:\Apps\anaconda\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
A:\Apps\anaconda\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
A:\Apps\anaconda\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
A:\Apps\anaconda\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


array([0.75324675, 0.72727273, 0.75974026, 0.82352941, 0.74509804])

In [16]:
score.mean()

0.7617774382480265

In [17]:
from sklearn.ensemble import RandomForestClassifier
score2=cross_val_score(RandomForestClassifier(),X,y,cv=5)
score2

array([0.72727273, 0.72727273, 0.77272727, 0.83006536, 0.77777778])

In [18]:
score2.mean()

0.7670231729055259